### ISSUE TITLE
ParseError when handling a statement containing a UUID

### ISSUE THREAD

**Issue by S4NT14G0** [lelit/pglast#124]
I have a statement as following:

```
statment =  """
    SELECT EXISTS (SELECT 1 
    FROM table_a
    WHERE id = a600966e-db8f-4be5-9c15-bbdba720e082) AS anon_1
"""
```

When I try to parse out the tables within this statement using:

```
tables = [
    table
    for table in pglast.visitors.referenced_relations(temporary_statement)
    if "pg_" not in table
]
```

It's failing with the following error:

```
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<string>", line 3, in <module>
  File "/Users/santiago/.virtualenvs/bravos/lib/python3.10/site-packages/pglast/visitors.py", line 488, in referenced_relations
    return ReferencedRelations()(parse_sql(stmt) if isinstance(stmt, str) else stmt)
  File "pglast/parser.pyx", line 276, in pglast.parser.parse_sql
pglast.parser.ParseError: syntax error at or near "be5", at index 238
```

This appears to be failing down at the C level, but it doesn't make sense due to [UUIDs](https://www.postgresql.org/docs/14/datatype-uuid.html) being a supported type in Postgres.

Here are some versions of relevant apps within my stack for reproducing:

Python 3.10.9
pglast==4.1
Postgres V14

I have crafted a temporary work around, but believe this to be an issue within the library.  For anyone who needs a temporary solution:

```
        # Oddly enough pglast doesn't support UUIDs inside of the statements.
        # The C code breaks when parsing despite UUID being valid PSQL types.
        uuid_regex_pattern = r"(?i)\b[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}\b"
        match = re.search(uuid_regex_pattern, statement)

        temporary_statement = statement
        if match:
            uuid = match.group()
            temporary_statement = temporary_statement.replace(uuid, f"'{uuid}'")
        self.read_tables = set(
            [
                table
                for table in pglast.visitors.referenced_relations(temporary_statement)
                if "pg_" not in table
            ]
        )
```

**Comment by S4NT14G0** [comment]
I realized that the parse was in fact correct and I was missing '' around my UUID which causes queries to break in posgres and pglast.
