### ISSUE TITLE
TypeError: object of type 'Missing' has no len()

### ISSUE THREAD

**Issue by apnewberry** [lelit/pglast#17]
I'm getting an error message here:

```sql
BEGIN;

CREATE MATERIALIZED VIEW a AS (
SELECT 1
FROM y
);

CREATE MATERIALIZED VIEW b AS (
SELECT 2
FROM y
);

ROLLBACK;

```

```
Traceback (most recent call last):
  File "/home/user/.local/venvs/pipx/bin/pgpp", line 10, in <module>
    sys.exit(main())
  File "/home/user/.local/venvs/pipx/lib/python3.6/site-packages/pglast/__main__.py", line 82, in main
    workhorse(args)
  File "/home/user/.local/venvs/pipx/lib/python3.6/site-packages/pglast/__main__.py", line 36, in workhorse
    comma_at_eoln=args.comma_at_eoln)
  File "/home/user/.local/venvs/pipx/lib/python3.6/site-packages/pglast/__init__.py", line 38, in prettify
    prettified = IndentedStream(**options)(Node(orig_pt))
  File "/home/user/.local/venvs/pipx/lib/python3.6/site-packages/pglast/printer.py", line 232, in __call__
    self.print_node(statement)
  File "/home/user/.local/venvs/pipx/lib/python3.6/site-packages/pglast/printer.py", line 357, in print_node
    printer(node, self)
  File "/home/user/.local/venvs/pipx/lib/python3.6/site-packages/pglast/printers/dml.py", line 634, in raw_stmt
    output.print_node(node.stmt)
  File "/home/user/.local/venvs/pipx/lib/python3.6/site-packages/pglast/printer.py", line 357, in print_node
    printer(node, self)
  File "/home/user/.local/venvs/pipx/lib/python3.6/site-packages/pglast/printers/ddl.py", line 600, in create_table_as_stmt
    and len(node.query.targetList[0].val.fields) == 1
TypeError: object of type 'Missing' has no len()

```

---
pglast 1.2

**Comment by lelit** [comment]
This seems to be fixed on current master.
Could you verify and report back please?

**Comment by apnewberry** [comment]
Yep, thanks!

**Comment by lelit** [comment]
Thank you for the confirm.
